# Generated by Django 4.1.5 on 2023-03-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("STUDENT", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="fullname",
        ),
        migrations.RemoveField(
            model_name="student",
            name="phone",
        ),
    ]
