# Generated by Django 4.1.5 on 2023-03-29 05:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("STUDENT", "0002_remove_student_fullname_remove_student_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
